apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-spring-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-spring-app
  template:
    metadata:
      labels:
        app: devops-spring-app
    spec:
      containers:
      - name: devops-spring-app
        image: devops-spring-app:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "devops-spring-app"
        - name: DD_ENV
          value: "production"
        - name: DD_VERSION
          value: "1.0.0"
        - name: BUGSNAG_API_KEY
          valueFrom:
            secretKeyRef:
              name: bugsnag-secret
              key: api-key
        - name: BUGSNAG_RELEASE_STAGE
          value: "production"
        - name: BUGSNAG_APP_TYPE
          value: "spring-boot"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-spring-app
  namespace: default
spec:
  selector:
    app: devops-spring-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer 