name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      
    - name: Run tests
      run: mvn test
      
    - name: Build Docker image
      run: docker build -t devops-demo:${{ github.sha }} .
      
    - name: Run container
      run: |
        docker run -d -p 8080:8080 --name devops-app devops-demo:${{ github.sha }}
        sleep 10
        curl http://localhost:8080/health
        docker stop devops-app
        docker rm devops-app
